### PR TITLE
Changed the way that each test table gets created

### PR DESCRIPTION
**Pull request by DannyDainton**
The test tables use `datatables` that add the search/filter/sorting functionally out of the box but this was being used in a non-efficient way. I've changed the script slightly to make it more performant.

### CODE REVIEW

**Comment by DannyDainton** [comment]
Hey @yyahav,

Could you grab this change and run it locally to see if it changes the table situation, please?

**Review by yyahav — APPROVED** [review]
@DannyDainton Great job! 👏 That fixed it, now I can see the Search and Sort on both iterations

**Comment by yyahav** [comment]
I can see what you did there... removed the id for the table and initialized DataTables per class instead of specific id...

I actually saw references online about that, when using the same id and the table already got rendered for the first iteration, the second one was not rendered correctly.
But how did it work on your env before the change?

And for some reason when I tried this solution I got double Search boxes, like here: https://stackoverflow.com/questions/13984698/datatables-showing-two-search-boxes-and-pagination-data

But now it's all good, great work and thank you so much! I really appreciate your support!!! 🙏🙏🙏

**Comment by DannyDainton** [comment]
Really strange, I can see occasions where it has been working and also not been working 😬 - Hopefully, this change brings it all back in line again. 🙏🏻

**Pull request merged**
