### PR TITLE
Fix SyntaxError occuring on Safari browser

### PR DESCRIPTION
**Pull request by sam-viz**
Hello,

First of all, thank you for creating such an awesome template !
I was trying to use it, but it didn't seem to work.

Screenshot 2019-06-28 at 16 34 21

After some digging, i found that there was an error which makes the report unreadable on Safari.
When trying to fetch iterations, safari throws a SyntaxError.

Screenshot 2019-06-28 at 16 43 15

I made a Quick fix and i hope if it is okay with you, to merge it and make a new release on npm.

Thank you.

### CODE REVIEW

**Comment by DannyDainton** [comment]
Hey,

Thanks for the support. ❤️

I'll have a look and get that sorted out. 

Probably won't get to it till after the weekend but if I do get time, I'll give you a shout.

**Comment by DannyDainton** [comment]
OK I made time - I published a new version. Let me know if that's done it for you.

Great catch, would never have seen that and for my sins and shocking as a Tester...I also open it in Chrome. My bad.

**Comment by sam-viz** [comment]
Thank you very much for your reactivity @DannyDainton ! 
The new version fixes the issue.

**Comment by DannyDainton** [comment]
You're welcome - I appreciate you finding and suggesting the fix for that issue. 

Please feel free to submit anything else you find or improvements you can make. The code is only as good as the person writing it and I'm learning all the time so you will see some _hacky_ areas in there for sure. :)

Thanks again.

**Pull request merged**
