### PR TITLE
Added a toggle button along side with the expand all to show only failures

### PR DESCRIPTION
**Pull request by praveendvd**
Added toggle button that allows to filter out only test failures.  

image

OnClicking the button:

image

Clicking again will show the first template

### CODE REVIEW

**Comment by DannyDainton** [comment]
I love the idea but not sure I'm keen on the placement, for a couple of reasons.

The expand/collapse button section is huge anyway so adding another button on the end to extend it doesn't feel right to me. 

Maybe if you also want to have a go at changing it the expand/collapse buttons to toggle on click rather than 2 separate ones, that might reduce the size.

Secondly, I think the context of the action is different to the, that more about showing the state of requests, rather than opening/closing them. 

I expiremented with something when I added the search field and have that filter failures toggle down by the search input.

**Comment by praveendvd** [comment]
> I love the idea and if works really well but not sure I'm keen on the placement/location, for a couple of reasons.
> 
> The expand/collapse button section is huge anyway so adding another button on the end to extend it doesn't feel right to me.
> 
> Maybe if you also want to have a go at changing it the expand/collapse buttons to toggle on click rather than 2 separate ones, that might reduce the size. Also, I think having to hit the button of the same name twice to see the non-fails again might confuse people
> 
> Secondly, I think the context of the action is different from the other ones that are more about just opening/closing the folders and requests.
> 
> I experimented with something when I added the search field and have that filter failure toggle down by the search input bu that only really worked if you have more than 18 iterations.
> 
> There are a few issues with the way you have it too if there are no fails in the report and you hit that button it will hide the passed request for no reason so maybe having it only show if there are failures. It also hides the iteration tab too :(
> 
> When you have to scroll down the page, I hide the rest of the toggle buttons but the horrible way that I have it, it leaves that new one still showing at the top. That whole button block can be changed and maybe come under a single action rather than individual ones.

Thanks Danny for the detailed response I will have a look at this ,:)   I have a report that had 200 iteration and 3 failed , I wanted to see only failed one , and this was the reason to bring in this . 

And about request with passed on hiding was done intensionally for the same reason when there are too many requests and user is interested in only failed . If the request needed not he hidden then the toggle could be added only to the iteration element . I will have a look thanks Danny :)

**Comment by DannyDainton** [comment]
I'm not saying it's bad of unwanted change, I think it would suit some usecases but not _all_ usecases. Which is obviously going to be impossible but we just need to think about the different reports that could be created.

There is an option flag to create a report that only shows failures and excludes all the passed requests. Slightly different usecase again and only covers a single usecase. 

I'm sure the way I had it was that I had a checkbox next to the search and that would filter the iterations down to only the ones that had failures in them. It was rubbish and had some quirks so I didn't push it forward.

I love that you're thinking of these new things to make the reporter better - happy to take a look through again that you want to add in 😁

**Comment by praveendvd** [comment]
Will surely try it and please do have a look when you get a time . :)

**Comment by praveendvd** [comment]
[newman.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/4603855/newman.zip)

Added sample reports : 

Following features are added:
1) Added show only failures , button that filters out all passed iterations and reqeusts and shpws only failed one.
2) Fixed show failure button not hidding on scroll 
3) Removed collapse buttons and added toggle functionality to Expand Folder and Expand Request
4) Verified that only one filter will be applied at a time, if show failure is clicked and user inputs a filter then filter value will be applied show failure filter will be removed.
5) if user had some filter values in place and user clicks show failure then filter is removed and show failure filter is applied

I also have created a branch :

https://github.com/praveendvd/newman-reporter-htmlextra/tree/showFailedIteration

With same features but making sure only itertaions are filtered and not requests (Sample reports are available inside failedIteration folder int he attached zip)

**Pull request closed without merging**
