### PR TITLE
Added ability to skip requests #308

### PR DESCRIPTION
**Pull request by praveendvd**
implements #308 

[new.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/6826416/new.zip)

final report

### CODE REVIEW

**Comment by praveendvd** [comment]
@DannyDainton  fixed merge conflict 🎉

**Comment by praveendvd** [comment]
@DannyDainton  When will new version be released ? npm doesn't have any new releases

**Comment by DannyDainton** [comment]
Not sure, when I have time.

It's 100% not going to be on a Sunday 😂

**Comment by praveendvd** [comment]
> Not sure, when I have time.
> 
> It's 100% not going to be on a Sunday 😂

Thought the npm publish workflow is broke , so asked 🤭 that it was executed but still no new releases . Just wanted to bring it your attention. 

Now fine ,,😁

**Comment by DannyDainton** [comment]
I know it's not working, I'm OK with that right now. Not a major priority in my life 😂

**Pull request merged**
