### PR TITLE
Add unclosed div tags

### PR DESCRIPTION
**Pull request by bassie1995**
We had issues embedding the reports in an HTML page, because some `div` tags are unclosed.

I think these are the ones we need to add, please verify :)

### CODE REVIEW

**Comment by DannyDainton** [comment]
Thanks for sorting this out, I'll take a look 😁

**Comment by DannyDainton** [comment]
Hey @bassie1995,
 
Just checked this using the default template and although it does have some unclosed tags (I'll sort that out) - When I created a report with the suggested change, the reports styling doesn't look quite right to me.

Screenshot 2020-01-07 at 11 23 54

Could you check locally, please?

**Comment by bassie1995** [comment]
Hi @DannyDainton, seems like I did, indeed, put the tags in the wrong place. That's why I figured I'd ask for a check! Thanks, I'll take a look.
Any suggestions for a food formatter? I've not found the formatting to be great in VS Code, with the setup I have.

**Comment by DannyDainton** [comment]
I was actually looking for one myself and I should probably add a test in there to check for things like that. I've used a tag highlighter plugin in the past but I can't think of the name of it.

The templates are a bit of a mess to be fair and I'm not really actively working on the reporter right now...well...unless something major comes up :)

**Comment by bassie1995** [comment]
I tried, but the tool didn't get the Handlebars tags... I think this new commit might be it, I was being stubborn last time but think they should be at the bottom.

Otherwise I'll have to count them manually :)

**Comment by DannyDainton** [comment]
That looks better to me - I'll pull in that change but I won't publish a new version just yet.

I want to look into adding a test for that somehow with a linter of something, not really thought that far ahead yet :)

**Pull request merged**
