### PR TITLE
Add skipping request headers, parts of requests

### PR DESCRIPTION
**Pull request by bassie1995**
Have a quick and dirty implementation, curious what you think about naming which is kind of awkward.
Complete Handlebars noob, so forgive me :)

Handlebars template I formatted for ease of use in my editor, I can revert if needed.

### CODE REVIEW

**Comment by DannyDainton** [comment]
I'm away at the moment so I won't be able to have a look to after the 23rd.

**Comment by bassie1995** [comment]
I was thinking about that and that was my initial implementation, but that ended up just creating more effort for me to keep my version updated (and we would have the same here?)

Which versions would you want to add? One without any request headers and one without any possibly-sensitive outputs?

**Comment by DannyDainton** [comment]
I'd lean towards something that hides or masks the Headers using a cli flag but I don't really want to add in something that removes the different sections of the report.

If folks want to do that, just create a template. That's why the reporters have that template option. 😁

**Comment by DannyDainton** [comment]
@bassie1995 do you mind taking a look at the conflicts, please? - Could you pull the latest changes and update the PR.

In terms of the PR, could we break it down into 2 separate ones - I like the ability to omit a particular header but not keen on adding the ability to remove different parts of the final report. I would prefer that folks create a custom template to do that.

**Comment by DannyDainton** [comment]
@bassie1995

Any feedback on this one? I'm not pulling in the changes as they are so I'm probably going to close this out until I can find a good solution for the Headers.

**Comment by bassie1995** [comment]
Sorry, didn't have time! Lots of changes and busy sprints. Want me to just include the header changes as-is?

**Comment by DannyDainton** [comment]
That would be cool, if you also wanted to add to the documentation to give
people an idea how they could use it, that would be awesome.

I can have a look at the new changes when I'm free. 🏆

**Comment by DannyDainton** [comment]
Hey @bassie1995,

I'm going to close this PR, it's really going anywhere and have been open for over 2 months. 

If you get some more time maybe we can have a chat about the changes and try to add some of them in again.

**Comment by bassie1995** [comment]
Hey Danny,

This is on my radar again, luckily! Have been wanting to get back to this.
I can separate the header for now, then would there be a way to make the skipping easier?

I was thinking I could do a single parameter, like hideSensitiveData or something, that then hides headers and bodies?

If not, I'll just make a new template and switch between the two on my end. Would appreciate not having to update it when you make a change, but shouldn't be too involved.

**Comment by DannyDainton** [comment]
Welcome back :)

That sounds good, a single param would be could if it was a `true/false` and `off` by default. With the change, we would just need to make sure that an entry is made in the README to tell folks that you _could_ use that option to do this.

**Comment by bassie1995** [comment]
Thanks! Happy to finally have some time to do this again, sorry for keeping this paused :(

You basically took the words right out of my mouth, except with better wording. I'll get to work and make a new PR.

**Pull request closed without merging**
