### PR TITLE
This pull request is to add functionality of skipping specific folder from the final report

### PR DESCRIPTION
**Pull request by praveendvd**
THis is as part of feature request #313

### CODE REVIEW

**Comment by praveendvd** [comment]
[new.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/6826199/new.zip)

Final report with folder1 and folder4 skipped

**Comment by DannyDainton** [comment]
Added an empty value is the first thing I tried - I've seen issues with this in the past with the other CLI flags. We'll need to handle that case.

image

**Comment by praveendvd** [comment]
Yes I forgot to push that fix I saw that , will do it today or tomorrow

**Comment by DannyDainton** [comment]
Nice one mate, not checked the request PR but is that a similar thing?

**Comment by praveendvd** [comment]
> Nice one mate, not checked the request PR but is that a similar thing?

Yes same approach but  on different element , have to do the same fix🎉😭

**Comment by praveendvd** [comment]
@DannyDainton  made that fix for both the pull request ,  thanks danny

**Comment by DannyDainton** [comment]
Hey @praveendvd,

I've tried multiple combinations and I've not been able to skip the folder using the `--reporter-htmlextra-skipFolders` flag 🤔 😢 

Would you be able to take a look or give me a command that I can run on my side and see this skipping the folder please.

**Comment by DannyDainton** [comment]
I was messing around and tried a method that I have for skipping the headers etc:

Having this in the template in the places where you added the `{{#unless (containsFolder parent.name)}}`
```
{{#isNotIn parent.name @root.skipFolders}}
...
{{/isNotIn}}
```

Add this to the bottom of the `lib/index.js`
```
skipFolders: options.skipFolders || []
```

You could test it using:

```
npx newman run https://www.getpostman.com/collections/6c2d3651ff2c67dbb95c -r htmlextra --reporter-htmlextra-skipFolders "Headers,Utilities"
```

**Comment by praveendvd** [comment]
@DannyDainton  i forgot to add the return 😆

**Comment by praveendvd** [comment]
@DannyDainton  added and tested both are working as expected now , should i change it ?

**Comment by praveendvd** [comment]
Thanks Dannny added that now :)

**Comment by DannyDainton** [comment]
Thanks for changing that.

It's a shame that the nested folders are not removed or that the top-level folder then doesn't hide the nested ones :(

**Comment by praveendvd** [comment]
Will look into that , it's interesting

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by praveendvd** [comment]
@DannyDainton  hi Danny parent.name gets "folder 1 / folder inside / next folder"  when used in handle bar , but when i pass it through Notin Register it is passed only as "folder 1"  do you have any suggestions

**Comment by praveendvd** [comment]
@DannyDainton  : 

console.log(_.includes("request1 Copy,folder 1", "request1")) this returns true as it compares string instead of exact element , this will be a problem for all Notin i guess , for folder i fixed it by spliting and converting it string array

**Comment by praveendvd** [comment]
Added case sensitive check ,  now nested folders and requests are filtered out ,

**Comment by DannyDainton** [comment]
Can you do a quick check and confirm the other flags that make use of that `isNotIn` helper, all work as expected?

I don't want to knock anything else out as a result of changing the function 😬

**Comment by praveendvd** [comment]
> Can you do a quick check and confirm the other flags that make use of that `isNotIn` helper, all work as expected?
> 
> I don't want to knock anything else out as a result of changing the function 😬

i didn't changed exisitng logic  , just added a if condition will check that too

**Comment by DannyDainton** [comment]
I know that but you also said that something was working when you tested it but then found that you didn't add a `return`...I'm just thinking about the wider users rather than what this one thing does at the moment :D

**Comment by praveendvd** [comment]
> I know that but you also said that something was working when you tested it but then found that you didn't add a `return`...I'm just thinking about the wider users rather than what this one thing does at the moment :D



That i reverted and retyped all things and forgot to put in return when doing the cosmetic changes 😆 . FIngers crossed this is tested and looks good . 


For exaple : `--reporter-htmlextra-skipHeaders "User-Agent praveen"` will skip User-Agent header 😆 


How is  skipenvironmentVars works

` --reporter-htmlextra-skipEnvironmentVars "test" --env-var "test=2"` 

i added it to url {{test}} and it gets resolved ( in current npm relase not just this PR) checked with skip header etc and it works as expected

**Comment by DannyDainton** [comment]
Cheers mate - I'm just super cautious when making these types of changes 😄 

I think there also need some extra attention given to the overall testing side of the project, to make that more meaningful and catch some of the _in report_ changes, I don;t think we do a good job at that right now - Nothing to do with this PR though, just thinking out loud 🤔

**Comment by praveendvd** [comment]
> Cheers mate - I'm just super cautious when making these types of changes 😄
> 
> I think there also need some extra attention given to the overall testing side of the project, to make that more meaningful and catch some of the _in report_ changes, I don;t think we do a good job at that right now - Nothing to do with this PR though, just thinking out loud 🤔

we need more unit test of functinality

**Pull request merged**
