### PR TITLE
Feature to mask specific value in the report generated

### PR DESCRIPTION
**Pull request by vkarthikvadivel**
Added a feature to mask the value of key specified in the response body of report generated. Added maskResponseKey option to provide the keys that need to be masked in the report.

### CODE REVIEW

**Comment by DannyDainton** [comment]
Hey @vkarthikvadivel

Thanks for submitting this PR, I'll take a look over the weekend/early next week.

Really appreciate you adding this feature!! 🏆

**Comment by vkarthikvadivel** [comment]
Sure @DannyDainton
Have a look and let know about it. I was using the reporter to generate reports and there was a ask to mask the JWT tokens from the report generated. I had to do a work around to accomplish it. So thought it would be better to add a feature to mask the response.

**Comment by DannyDainton** [comment]
Can you talk me through what the expected outcome of this would be?

If I use `--reporter-htmlextra-maskResponseKey a` for instance, it will mask the _whole_ response body and the same if I use a number too `--reporter-htmlextra-maskResponseKey 1`. I could add something that isn't part of the response body `blah` and it would mask the whole thing because that is _something_ in the array.

If it's just going to mask the whole response, it might as well be a boolean rather than a list of values in an array.

Screenshot 2020-05-16 at 14 07 04

I'm not sure if that was the intention? 

My understanding would be that this would check the response body and _if_ a key (specified in the array) matched one in the body, it would mask _just_ that key and not the whole response. 

What happens if users want to mask a couple of properties in the response but want to still be able to view the rest?

**Comment by DannyDainton** [comment]
I was messing about in the app and wrote this to mask certain details of the response body, I needed to bring in a different version of Lodash to access some of the _newer_ methods: 

```javascript
let maskValue = '*******',
	ld = require('lodash');

let masker = ld.cloneDeepWith(pm.response.json(), (value, key) => {
	if (_.some(['url', 'test', 'cookie'], item => ld.toLower(key) === ld.toLower(item))) {
		return maskValue;
	}
	if (ld.isObject(value)) {
		return;
	}
	return value;
})

console.log(masker)
```

This would return something like this to the console, it masks the values for the keys specified. Is this the kind of outcome you had in mind for the report?

Screenshot 2020-05-17 at 08 49 45

**Comment by vkarthikvadivel** [comment]
> I was messing about in the app and wrote this to mask certain details of the response body, I needed to bring in a different version of Lodash to access some of the _newer_ methods:
> 
> ```js
> let maskValue = '*******',
> 	ld = require('lodash');
> 
> let masker = ld.cloneDeepWith(pm.response.json(), (value, key) => {
> 	if (_.some(['url', 'test', 'cookie'], item => ld.toLower(key) === ld.toLower(item))) {
> 		return maskValue;
> 	}
> 	if (ld.isObject(value)) {
> 		return;
> 	}
> 	return value;
> })
> 
> console.log(masker)
> ```
> 
> This would return something like this to the console, it masks the values for the keys specified. Is this the kind of outcome you had in mind for the report?
> 
> Screenshot 2020-05-17 at 08 49 45

Yes @DannyDainton 
This is what is expected to be generated from the report.

**Comment by DannyDainton** [comment]
It's not happening when I run what you have in place. 😁

The response body on the report, if I add anything to the new flag is `"********"` it doesn't mask the individual value.

Can you add a screenshpt of a recording of what's happening for you please?

**Comment by vkarthikvadivel** [comment]
I didn't know XML payloads were also used. Parser would fail for XML response. Let me look into that case as well and come back. May be you could close the merge request.

**Comment by DannyDainton** [comment]
Are you using a different template for your report? 

I don't see the same on the reports that I have generated with the code from this PR.

Are you using a script to run this and not from the CLI?

**Comment by DannyDainton** [comment]
Just trying a few other collections, I see it's returning a failure in the reporter if it tries to parse anything else that's not JSON....so a 404 that might return a HTML response etc.

This is more than likely working for your use case but would fail for many other which is something that I need to account for as this change would impact every reporter.

**Comment by vkarthikvadivel** [comment]
Will look at the possible cases and get back to you. Thanks for your time in looking into this PR.

**Comment by DannyDainton** [comment]
No worries, I like the direction where this is heading but I don't think it's quite there yet and different responses would easier break it 😢

I look forward to seeing what you can come up with, I'll have a go at doing it too 😁

**Pull request closed without merging**
