### PR TITLE
Update index.js for Object to Json helper

### PR DESCRIPTION
**Pull request by mbooch22**
Need a new helper that can convert all Objects to Json. 

Context.forEach doesn't work when trying to get all Failed test cases.

### CODE REVIEW

**Comment by DannyDainton** [comment]
Could you show me a visual example of how you're using that helper in a template - For context 😁

**Comment by mbooch22** [comment]
@DannyDainton 
For example, to get all failures as an object in summary.failures,  "let oFailures = {{{formdata failures}}};" would not work as the formdata function would return an empty object.

**Comment by mbooch22** [comment]
"let oFailures = JSON.parse({{{object failures}}})" in summary.failures would return all the failures as an object.

**Comment by DannyDainton** [comment]
How are you going to be using that in a template? What's it going to look like?

I've obviously created a generic default template with a bunch of stuff on it and I'm always interested to see how other people are using the reporter with custom templates 😁

**Comment by mbooch22** [comment]
@DannyDainton The plan is to group the Failed Test cases by EndPoint/ErrorMessage so that users don't have thousands of tests to look through individually. Currently we are looping through each test case using the standard handlebar syntax. However that is causing a size issue with the template as it prints out each loop.
We are still developing this solution but hopefully on the Failed Test case tab we can navigate to failed Test cases through new groupings.

**Comment by DannyDainton** [comment]
I'd be very interested to see what you come up with 🏆

**Comment by mbooch22** [comment]
@DannyDainton Will do. I'll try and share a screenshot or something once it is complete. Thanks!

**Comment by DannyDainton** [comment]
Out of interest, was there nothing in here that would do the job for you?

https://github.com/helpers/handlebars-helpers

These helpers are also included with the reporter

**Comment by mbooch22** [comment]
@DannyDainton Wow, I was not aware these were included in the reporter. Exactly what I needed!!! Thanks so much!
I guess you can close this PR. 
Thanks again!

**Comment by DannyDainton** [comment]
I included them to enhance the creation of custom templates as there are certain limitation to the standard handlebar helpers.

**Pull request merged**
