### PR TITLE
Fix for mark up table issue #322

### PR DESCRIPTION
**Pull request by praveendvd**
image

### CODE REVIEW

**Comment by praveendvd** [comment]
[report.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/6822528/report.zip)

example report with tests and requests

**Comment by DannyDainton** [comment]
I'll take a look this afternoon when I get some free time.

Thanks for taking a look at this one @praveendvd ❤️

**Comment by DannyDainton** [comment]
I think it looks fine apart from the change in style on reload. It's rendering the text with the CDN script and then applying the CSS styles. 🤔 Not sure I like the what it's doing there. 😢 

https://user-images.githubusercontent.com/17089546/125786778-3ea24ff6-9366-4b03-9c6a-363bf72c3de1.mp4

**Comment by praveendvd** [comment]
@DannyDainton  hi danny i think that is caused even without that fix , could you have a look ?

**Comment by praveendvd** [comment]
@DannyDainton  i think its a issue with chrome version

**Comment by DannyDainton** [comment]
You're probably right and looking closer at it today has made it more prominent.

I'll take another look through that later.

**Comment by praveendvd** [comment]
> You're probably right and looking closer at it today has made it more prominent.
> 
> I'll take another look through that later.
```
body.theme-dark code {
    color: #ccd2d8!important;
} 

body.theme-light code {
    color: #000000!important;
} 

```

**Comment by praveendvd** [comment]
these important style are causing the color changes

**Comment by DannyDainton** [comment]
I'm sure I added that for a different reason...not really sure why now 😂

**Comment by praveendvd** [comment]
[new.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/6823370/new.zip)


if i remove that it will look like this

**Pull request merged**
